import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  ...compat.config({ extends: ['next/core-web-vitals', 'next/typescript'] }),
  // next-env.d.ts is generated by Next (and gitignored); it is not ours to lint.
  { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
];

export default eslintConfig;
